# Prepare the data

In [101]:
# Load the data
import pandas as pd
import numpy as np

high_popularity_data = pd.read_csv('../data/raw/high_popularity_spotify_data.csv', na_values=["", "NaN", "-", "null", "Null", "none", "None"])
low_popularity_data = pd.read_csv('../data/raw/low_popularity_spotify_data.csv', na_values=["", "NaN", "-", "null", "Null", "none", "None"])


# Drop NaNs and irrelevant columns, define features array and target variable
high_popularity_data = high_popularity_data.dropna()
low_popularity_data = low_popularity_data.dropna()
low_popularity_data.drop_duplicates(inplace=True)
high_popularity_data.drop_duplicates(inplace=True)

print(high_popularity_data.columns.sort_values())
print(low_popularity_data.columns.sort_values())

Index(['acousticness', 'analysis_url', 'danceability', 'duration_ms', 'energy',
       'id', 'instrumentalness', 'key', 'liveness', 'loudness', 'mode',
       'playlist_genre', 'playlist_id', 'playlist_name', 'playlist_subgenre',
       'speechiness', 'tempo', 'time_signature', 'track_album_id',
       'track_album_name', 'track_album_release_date', 'track_artist',
       'track_href', 'track_id', 'track_name', 'track_popularity', 'type',
       'uri', 'valence'],
      dtype='str')
Index(['acousticness', 'analysis_url', 'danceability', 'duration_ms', 'energy',
       'id', 'instrumentalness', 'key', 'liveness', 'loudness', 'mode',
       'playlist_genre', 'playlist_id', 'playlist_name', 'playlist_subgenre',
       'speechiness', 'tempo', 'time_signature', 'track_album_id',
       'track_album_name', 'track_album_release_date', 'track_artist',
       'track_href', 'track_id', 'track_name', 'track_popularity', 'type',
       'uri', 'valence'],
      dtype='str')

In [102]:
low_popularity_data.describe()

,time_signature,track_popularity,speechiness,danceability,duration_ms,energy,mode,instrumentalness,valence,key,tempo,loudness,acousticness,liveness
count,3144.000000,3144.000000,3144.000000,3144.000000,3.144000e+03,3144.000000,3144.000000,3144.000000,3144.000000,3144.000000,3144.000000,3144.000000,3144.000000,3144.000000
mean,3.929389,43.477099,0.102174,0.607268,2.016402e+05,0.543509,0.553435,0.286603,0.458438,5.177163,116.766884,-10.663833,0.405567,0.165487
std,0.447827,14.823668,0.101726,0.200372,9.157390e+04,0.263635,0.497216,0.395181,0.266140,3.565412,29.152400,8.155066,0.342249,0.124652
min,1.000000,11.000000,0.021900,0.058900,3.537500e+04,0.000202,0.000000,0.000000,0.029600,0.000000,48.232000,-48.069000,0.000004,0.022000
25%,4.000000,32.000000,0.038800,0.509000,1.518962e+05,0.357750,0.000000,0.000000,0.232000,2.000000,94.889250,-11.999750,0.084100,0.096400
50%,4.000000,46.000000,0.055000,0.649500,1.846410e+05,0.592000,1.000000,0.001060,0.462000,5.000000,116.052000,-8.026000,0.316000,0.116000
75%,4.000000,55.000000,0.118000,0.753000,2.264302e+05,0.747000,1.000000,0.788000,0.673000,8.000000,136.706500,-5.831000,0.725250,0.189000
max,5.000000,68.000000,0.927000,0.977000,1.355260e+06,0.998000,1.000000,0.991000,0.987000,11.000000,241.426000,1.318000,0.996000,0.979000

In [103]:
high_popularity_data.describe()

,energy,tempo,danceability,loudness,liveness,valence,time_signature,speechiness,track_popularity,instrumentalness,mode,key,duration_ms,acousticness
count,1685.000000,1685.000000,1685.000000,1685.000000,1685.000000,1685.000000,1685.000000,1685.000000,1685.000000,1685.000000,1685.000000,1685.000000,1685.000000,1685.000000
mean,0.667062,121.079900,0.650343,-6.706617,0.171568,0.525538,3.950148,0.100950,75.807715,0.041545,0.578635,5.339466,214592.821365,0.221327
std,0.184855,27.071562,0.157766,3.376527,0.123989,0.236043,0.326767,0.099773,6.033935,0.156599,0.493924,3.608829,58314.431173,0.250628
min,0.001610,49.305000,0.136000,-43.643000,0.021000,0.034800,1.000000,0.023200,68.000000,0.000000,0.000000,0.000000,61673.000000,0.000013
25%,0.551000,100.053000,0.543000,-7.961000,0.093400,0.339000,4.000000,0.037900,71.000000,0.000000,0.000000,2.000000,176658.000000,0.023000
50%,0.689000,120.001000,0.664000,-5.976000,0.121000,0.528000,4.000000,0.058100,75.000000,0.000006,1.000000,5.000000,211200.000000,0.125000
75%,0.807000,136.902000,0.769000,-4.691000,0.210000,0.720000,4.000000,0.118000,79.000000,0.000814,1.000000,8.000000,245000.000000,0.335000
max,0.990000,209.688000,0.979000,1.295000,0.950000,0.978000,5.000000,0.848000,100.000000,0.971000,1.000000,11.000000,547107.000000,0.995000

In [104]:
high_popularity_data['type'].unique()

<ArrowStringArray>
['audio_features']
Length: 1, dtype: str

In [105]:
# remane 'playlist_genre' column to "genre"
high_popularity_data = high_popularity_data.rename(columns={'playlist_genre': 'track_genre'})
low_popularity_data = low_popularity_data.rename(columns={'playlist_genre': 'track_genre'})

In [106]:
high_popularity_data.to_parquet('../data/interim/high_popularity_data_orig.parquet')
low_popularity_data.to_parquet('../data/interim/low_popularity_data_orig.parquet')

orig_joined_data = pd.concat([low_popularity_data, high_popularity_data], ignore_index=True)

orig_joined_data.to_parquet("../data/interim/orig_joined_data.parquet")


high_popularity_data = high_popularity_data.drop(columns=['track_artist', 'analysis_url', 'id', 'playlist_id', 'playlist_name', 'playlist_subgenre', 'track_album_id', 'track_album_name', 'track_album_release_date', 'track_href', 'track_id', 'track_name', 'type', 'uri'])
high_popularity_data = low_popularity_data.drop(columns=['track_artist', 'analysis_url', 'id', 'playlist_id', 'playlist_name', 'playlist_subgenre', 'track_album_id', 'track_album_name', 'track_album_release_date', 'track_href', 'track_id', 'track_name', 'type', 'uri'])
joined_data = orig_joined_data.drop(columns=['track_artist', 'analysis_url', 'id', 'playlist_id', 'playlist_name', 'playlist_subgenre', 'track_album_id', 'track_album_name', 'track_album_release_date', 'track_href', 'track_id', 'track_name', 'type', 'uri'])

high_popularity_data.to_parquet('../data/interim/high_popularity_data.parquet')
low_popularity_data.to_parquet('../data/interim/low_popularity_data.parquet')
joined_data.to_parquet("../data/interim/joined_data.parquet")